### PR TITLE
(#52) Fix dependency cycle

### LINKED ISSUE #52: Setting wireguard::interaces causes a dependency cycle
## Affected Puppet, Ruby, OS and module versions/distributions

- Puppet: 7.16.0
- Ruby: 2.7.6
- Distribution: any
- Module version: 1.1.1-rc0

## How to reproduce (e.g Puppet code you use)
Set `wireguard::interfaces` in Hiera and `include wireguard`.

## What are you seeing
```
Error: Found 1 dependency cycle:
(Exec[generate public key wg0] => Wireguard::Interface[wg0] => Class[Wireguard] => Wireguard::Interface[wg0] => Exec[generate public key wg0])\nTry the '--graph' option and opening the resulting '.dot' file in OmniGraffle or GraphViz
Error: Failed to apply catalog: One or more resource dependency cycles detected in graph
```

## What behaviour did you expect instead
Clean Puppet run

## Any additional information you'd like to impart
The problem is a `require` instead of an `include` in the `wireguard::interface` defined type.  PR incoming.

### PR DESCRIPTION
**Pull request by silug**
#### Pull Request (PR) description
This tests the `$wireguard::interfaces` parameter and removes a dependency cycle.

#### This Pull Request (PR) fixes the following issues
Fixes #52

### CODE REVIEW

**Comment by smortex** [comment]
The project test suite is passing, so the dependency cycle looks odd.  Can you describe your usage of the module?

**Comment by smortex** [comment]
Ha, saw "Set wireguard::interfaces in Hiera and include wireguard.".  So #35 introduce a code smell that simply does not work?  Maybe we can just revert that (and maybe take a position in respect to this kind of usage of Hiera at the vox level)?

**Review by bastelfreak — APPROVED** [review]
@smortex I think merging this is fine. The change from require to include makes sense and we didn't notice this initially because we had no tests for the interfaces parameter

**Comment by smortex** [comment]
I don't like this but nothing mandates me of using this so i am fine :-D  I just see that the extra code of this feature I don't like cause trouble from time to time.

**Comment by silug** [comment]
@bastelfreak I rebased and dropped the extra test that I had added to spec/defines/interface_spec.rb.  Mind re-reviewing?

**Pull request merged**
